### ISSUE TITLE
הצעה לשיפור אחד הגרפים בפרק בדיקת השערות

### ISSUE THREAD

**Issue by rkportal** [adisarid/hebrewr#1]
יישר כוח, ספר מצוין ועבודה חשובה בשפה העברית
הצעה קטנה - [בגרף העמודות בפרק בדיקת ההשערות](https://www.hebrewr.co.il/06-hypothesis-tests.html#fig-539a35d47e664c97a50115a146a7f1bd-6), הייתי משתמש ב-geom_text במקום geon_label וממרכז. כלומר:
`penguins %>% 
    count(year, species) %>%
    group_by(year) %>% 
    mutate(prop = n/sum(n)) %>% 
    ggplot(aes(x = factor(year), y = prop, fill = species)) + 
    geom_col(position = position_fill()) + 
    scale_y_continuous(labels = scales::percent) + 
    ylab("Sample distribution") + xlab("") +
    ggtitle("Sample distribution of species over years") +
    geom_text(aes(label = glue::glue("{round(prop*100)}%")),
               position = position_fill(vjust = 0.5), show.legend = FALSE)
`
לא חיוני, אבל אישית אני חושב שישפר את הנראות.
רועי

**Comment by adisarid** [comment]
Thanks for the suggestion, chart has been revised. I'm glad you found the book useful, and feel welcome to raise additional suggestions. @rkportal
